from django.db import models
from django.contrib.auth.models import User

class UserInfo(models.Model):
	user = models.OneToOneField(User, primary_key=True)
	experience = models.TextField(null=True, blank=True)
	salary = models.IntegerField(null=True, blank=True)
	otr = models.TextField(null=True, blank=True)
	regional = models.TextField(null=True, blank=True)
	dedicated = models.TextField(null=True, blank=True)
	local = models.TextField(null=True, blank=True)
	intermodal = models.TextField(null=True, blank=True)
	bulk = models.TextField(null=True, blank=True)
	solo = models.TextField(null=True, blank=True)
	team = models.TextField(null=True, blank=True)
	ownerop = models.TextField(null=True, blank=True)
	freight = models.TextField(null=True, blank=True)
	van = models.TextField(null=True, blank=True)
	flatbed = models.TextField(null=True, blank=True)
	tanker = models.TextField(null=True, blank=True)
	elogs = models.TextField(null=True, blank=True)
	none = models.TextField(null=True, blank=True)
	hazmat = models.TextField(null=True, blank=True)
	doubles = models.TextField(null=True, blank=True)
	xtanker = models.TextField(null=True, blank=True)
	miles = models.TextField(null=True, blank=True)
	med = models.TextField(null=True, blank=True)
	dental = models.TextField(null=True, blank=True)
	vision = models.TextField(null=True, blank=True)
	life = models.TextField(null=True, blank=True)
	pets = models.TextField(null=True, blank=True)
	riders = models.TextField(null=True, blank=True)

class Company(models.Model):
	name = models.TextField()
	phone = models.CharField(max_length=13)
	email = models.EmailField()
	salary = models.IntegerField()
	distance = models.TextField()
	driver_type = models.TextField()
	benefits = models.TextField()
	equipment = models.TextField()
	freight = models.TextField()
	elogs = models.TextField()
	endorsements = models.TextField()
	miles = models.IntegerField()
	pets = models.TextField()
	riders = models.TextField()
	experience = models.IntegerField()
	url = models.TextField()

class Result(models.Model):
	user = models.ForeignKey(User)
	company = models.ForeignKey(Company)
